import { getFromCache, setInCache, deleteFromCache, getCacheStats, warmCache } from './src/utils/cache.js';

console.log('🧪 Testing Redis Caching Implementation...\n');

async function testCaching() {
  try {
    // Test basic set/get
    console.log('1. Testing basic cache operations...');
    const testKey = 'test:form:123';
    const testData = { 
      formName: 'Test Facility',
      fields: ['field1', 'field2'],
      createdAt: new Date().toISOString()
    };
    
    // Set cache
    const setResult = await setInCache(testKey, testData, 60); // 1 minute TTL
    console.log('✅ Set cache result:', setResult);
    
    // Get cache
    const cachedData = await getFromCache(testKey);
    console.log('✅ Retrieved from cache:', cachedData ? 'SUCCESS' : 'FAILED');
    
    // Test cache warming
    console.log('\n2. Testing cache warming...');
    const warmedData = await warmCache('test:warm:456', async () => {
      return { message: 'This was generated by cache warming', timestamp: Date.now() };
    }, 120);
    console.log('✅ Cache warming result:', warmedData ? 'SUCCESS' : 'FAILED');
    
    // Test cache statistics
    console.log('\n3. Testing cache statistics...');
    const stats = await getCacheStats();
    if (stats) {
      console.log('✅ Cache Statistics:');
      console.log('   Connected Clients:', stats.connected_clients);
      console.log('   Memory Usage:', stats.used_memory);
      console.log('   Hit Rate:', stats.hit_rate);
    } else {
      console.log('⚠️  Cache stats not available (Redis might not be configured)');
    }
    
    // Test pattern deletion
    console.log('\n4. Testing pattern deletion...');
    const deleteResult = await deleteFromCache('test:*');
    console.log('✅ Deleted pattern result:', deleteResult);
    
    console.log('\n🎉 All cache tests completed!');
    
  } catch (error) {
    console.error('❌ Cache test failed:', error.message);
  }
}

// Run the test
testCaching();